### ISSUE TITLE
is-email? Regular expression is overly restrictive

### ISSUE THREAD

**Issue by pmn** [noir-clojure/noir#13]
The regular expression in use in validation/is-email? rejects some email addresses that should be valid according to RFC 2822. 

For example, emails containing apostrophes and/or backticks are valid, but rejected by the regular expression in use. 

The following regular expression is a little more permissive. I can submit a patch if you'd like, but I wasn't sure what your preferences were. 

Here is the more permissive regex: 

```
#"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?
```

Noir is awesome by the way, thanks for making it!

**Comment by ibdknox** [comment]
ah, good catch. I think I grabbed the on I'm using from one of the standard regex repos. Yours looks better :) Can you submit a pull request with a couple tests as well?
