### ISSUE TITLE
tomcat 404

### ISSUE THREAD

**Issue by jedahu** [noir-clojure/noir#26]
Using `lein ring uberwar` and deploying a noir hello world project to tomcat6 results in a 404 for /welcome.

Project created with `lein noir new noir-test`. The only changes were the insertion of the following into project.clj:

```
    :dev-dependencies [[lein-ring "0.4.5"]]
    :ring {:handler noir-test.server/handler}
```

and in src/noir_test/server.clj:

```
    (def handler
      (server/gen-handler {:mode :dev :ns 'noir-test}))
```

The result was the same for :mode :prod.

FWIW, deploying compojure-example to tomcat works fine.

**Comment by ibdknox** [comment]
Hey Jedahu,

There was a topic on the mailing list about this a while ago:

https://groups.google.com/forum/#!topic/clj-noir/QNEzGfS8uUQ/discussion

Basically the gist is that you need to change the line that loads views to
either require them individually, or if you use noir 1.1.1-SNAPSHOT use:

(server/load-views-ns 'my-project.views)

Cheers,
Chris.

**Comment by jedahu** [comment]
Hi Chris,

Changing to noir-1.1.1-SNAPSHOT and using server/load-views-ns doesn't clear up the problem.

I have uploaded the test project to git://github.com/jedahu/noir-test2.git in case anyone wants to replicate the experiment

**Comment by ibdknox** [comment]
Apparently the classpath doesn't get setup in such a way that I can read it using the tools.ns stuff. Simply requiring the views at the top of your file will work just fine though:

(ns noir-test2
 (:require [noir-test2.views.welcome]))
