### ISSUE TITLE
has-values? doesn't match documentation

### ISSUE THREAD

**Issue by sjl** [noir-clojure/noir#30]
Maybe I'm just misunderstanding the documentation, but the docstring says:

```
"Returns true if all members of the collection has-value? This works on maps as well."
```

From reading that I would expect it to work like this:

```
(has-values? ["foo" "bar"])
; true

(has-values? ["foo" ""])
; false
```

But instead I seem to get a sequence of true/false values:

```
(has-values? ["foo" ""])
; (true false)
```

**Comment by ibdknox** [comment]
Definitely a bug. Fixed it and repushed to clojars.

To see the change you'll need to remove the noir 1.2.0 jar from your local cache at ~/.m2

Cheers,
Chris.
