### ISSUE TITLE
pre-route doesn't work with a regex in the URL

### ISSUE THREAD

**Issue by sjl** [noir-clojure/noir#31]
This:

```
(pre-route [:get ["/:anything" :anything #".+"]] {:keys [anything]}
           ... do something ...)
```

Fails with:

```
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IPersistentVector
```

**Comment by ibdknox** [comment]
hm, what version of Noir are you using?

**Comment by ibdknox** [comment]
I tried this in 1.2.0 and it works fine. There's an orthogonal issue, which I just fixed. I'll push that up now.

**Comment by sjl** [comment]
I'm using 1.2.  Here's the app, if you put that pre-route at the bottom of views/main.clj it will break: https://github.com/sjl/newseasons

**Comment by ibdknox** [comment]
I don't have vagrant installed so I can't run your app easily, but my minimal examples work fine. Try running this gist in a repl: https://gist.github.com/60fd1c2f22ceafa00edc

There was a different bug in comparing the route when the url wasn't a string, so you if it doesn't work with your copy of 1.2.0 you probably needed to delete the cached version in ~/.m2 or you can just use 1.2.1-SNAPSHOT.

**Comment by ibdknox** [comment]
Closing since I haven't heard back. If it's still an issue, feel free to reopen.
