### ISSUE TITLE
Route params with period character don't work

### ISSUE THREAD

**Issue by kzar** [noir-clojure/noir#35]
Routes that take a parameter break when the parameter contain the "." period character.

For example:

```
  (defpage "/blog/view/:id" {:keys [id]}
    (html5 [:h1 id]))
```

Matches `"/blog/view/some-post-id"` but not `"/blog/view/some.post-id"`

(Some of my post IDs hit this problem, for example "fixing-spotify-uxtheme.dll-error-on-windows-2000".)

Cheers, Dave.

**Comment by ibdknox** [comment]
Hey Dave,

You can change what it will match on using a regex:

``` clojure
(defpage [:get ["/blog/view/:id" :id #".+"]] {:keys [id]}
    (str "hey " id))
```

That will then match anything, including things with a period.

Cheers,
Chris.

**Comment by kzar** [comment]
Ah, thanks I didn't realise that!
