### ISSUE TITLE
can't get :servlet-request from (ring-request)

### ISSUE THREAD

**Issue by gzeureka** [noir-clojure/noir#40]
Is is the right way to get the HttpServletRequest object from the ring request map?

```
(ns my-app
    (:use noir.request))
(defpage [:get "/app"] []
   (str (ring-request)))
```

the map return by (ring-request) does contain the :servlet-request key, but the value is nil.  The values of :servlet-context, :servlet-response are also nil. The following is the content of the map:

{:remote-addr "127.0.0.1", :scheme :http, :query-params {}, :session {}, :form-params {}, :multipart-params {}, :servlet #, :request-method :get, :query-string nil, :content-type nil, :cookies {"ring-session" {:value "eb509a65-d33a-40d2-9646-e2ff785428b0"}}, :uri "/app", :server-name "127.0.0.1", :params {}, :headers {"cookie" "ring-session=eb509a65-d33a-40d2-9646-e2ff785428b0", "accept-charset" "GBK,utf-8;q=0.7,_;q=0.3", "accept-language" "en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4", "accept-encoding" "gzip,deflate,sdch", "accept" "text/html,application/xhtml+xml,application/xml;q=0.9,_/*;q=0.8", "user-agent" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.106 Safari/535.2", "connection" "keep-alive", "host" "127.0.0.1:8080"}, :servlet-request #, :content-length nil, :server-port 8080, :character-encoding nil, :servlet-response #, :body #, :servlet-context #}

**Comment by ibdknox** [comment]
see my response here: https://groups.google.com/d/msg/clj-noir/nH3f2rqCRt4/DYFewyKY7SkJ
