### ISSUE TITLE
lein noir new project skeleton doesn't survive noir upgrade 

### ISSUE THREAD

**Issue by kschuetz** [noir-clojure/noir#44]
The "welcome.clj" in my project was created by lein-noir 1.2.0.  When I upgraded to noir-1.2.1 my project wouldn't compile.

This was due to the requiring of [noir.content.pages :as pages] which no longer exists in 1.2.1.

**Comment by ibdknox** [comment]
mentioned in both the release announcement: https://groups.google.com/d/msg/clj-noir/llDUdYILGsw/5Q8h94h-jnkJ
and the changelog: https://github.com/ibdknox/noir/blob/master/history.md

The readme and website also point to installing lein-noir 1.2.1, which has the updated projects in it. Just installing the new plugin should get you on your way.

In general, you want to remove that require as soon as you're up and running.

Cheers,
Chris.
