### ISSUE TITLE
Request for get-errors to allow for zero args

### ISSUE THREAD

**Issue by mefesto** [noir-clojure/noir#47]
`noir.validation/errors?` allows you to optionally specify a field to determine if there are any associated errors. If you omit the field then it checks all fields. This issue is to request for similar behavior from `noir.validation/get-errors`.

This would help in the case where you'd like to display _all_ errors messages in a single location instead of next to the associated field.

**Comment by ibdknox** [comment]
Done in 1.2.2-SNAPSHOT :)
