### ISSUE TITLE
webnoir.org not responding

### ISSUE THREAD

**Issue by amalloy** [noir-clojure/noir#51]
Someone reported in #clojure that webnoir.org is down. @ibdknox, I don't know any way to get hold of you besides IRC/github, and I thought you'd want to know, so here's a github issue.

**Comment by ibdknox** [comment]
Forgot to respond to this. Thank you sir! I was on a boat at the time, but once I got home I fixed it. Amazon was nice enough to restart all my servers without restoring them... :/

Thanks again!
