### ISSUE TITLE
. not matched

### ISSUE THREAD

**Issue by ghost** [noir-clojure/noir#52]
Hi.

I'm trying to pass a value in the URL that contains the "." character but the route matching does not seem to work.
Below is the test to expose this. I did basically the same test in latest clout and compojure code and it works fine there. 

``` clojure
(defpage "/test/:id" {:keys [id]} id)

(deftest route-decoding-dot
  (-> (send-request "/test/x.y.z")
    (has-status 200)
    (has-body "x.y.z")))
```

Thank you.

**Comment by ibdknox** [comment]
What version of Noir are you using? This works in 1.2.2-SNAPSHOT. I believe this was an issue in compojure/clout previously and 1.2.2 is using the latest.

**Comment by ghost** [comment]
Hi Chris.
I was using 1.2.1.
Tried 1.2.2 just now and the problem still manifests.

**Comment by ibdknox** [comment]
I just ran the following in a repl:

``` clojure
(use 'noir.server 'noir.core)
(defpage "/test/:email" {:keys [email]} email)
(start 8083)
```

And then went to `http://localhost:8083/test/chris@gmail.com` and saw "chris@gmail.com". I also tried it with `chris%40gmail.com` and `chris.gmail.com` too.

Are you certain you ran it against 1.2.2-SNAPSHOT? (did deps and all that)

**Comment by ghost** [comment]
This is strange.

Yes, looks like I am using noir-1.2.2-20111019.122151-13.jar

Did the same on a remote machine and I get the same failure,

"We seem to have lost that one.
Since we couldn't find the page you were looking for, check to make sure the address is correct."

**Comment by ibdknox** [comment]
Do you by chance have multiple versions of clout or compojure in your lib directory?

**Comment by weavejester** [comment]
Matching the "." character is a change that is only in 1.0.0-SNAPSHOT of Compojure and 1.0.0-RC1 of Clout, so if you have any older version it won't work.

I'm going to release an RC soon of Compojure 1.0.0, so you shouldn't need to depend on snapshots for much longer.

**Comment by ibdknox** [comment]
Thanks James! Do you have any idea when 1.0.0 will hit shelves? I want to hold off an official 1.2.2 until then :)

**Comment by ghost** [comment]
Hi James.

It seems that Noir 1.2.2-SNAPSHOT is already using the versions mentioned by you:

compojure-1.0.0-20111019.122151-1.jar
clout-1.0.0-RC1.jar
ring-1.0.0-RC5.jar
ring-core-1.0.0-RC2.jar

**Comment by ghost** [comment]
EDIT: 
This actually works when testing in the Clout directory cloned from GitHub. So it just does not seem to work in my Noir setup.

---

Hi James.

I tracked the changeset to https://github.com/weavejester/clout/commit/0107b4e291b9ad89de8674706f9a59252479fa53
Checked my local source file and it has that change.

However, I did this test using Clout 1.0.0-RC1

``` clojure
(use 'ring.mock.request 'clout.core)
```

Expected: `{:id "x.y"}`

``` clojure
(route-matches (route-compile "/test/:id") (request :get "/test/x.y"))
nil
```

Explicitly specifying the regex makes it work:

``` clojure
(route-matches (route-compile "/test/:id" {:id #"[^/,;?]+"}) (request :get "/test/x.y"))
{:id "x.y"}
```

**Comment by weavejester** [comment]
Are you _certain_ you're using 1.0.0-RC1? Have you checked your lib and lib/dev directories?

When I run the same code, I get completely different results:

``` clojure
user> (use 'clout.core 'ring.mock.request)
nil
user> (route-matches (route-compile "/test/:id") (request :get "/test/x.y"))
{:id "x.y"}
```

**Comment by weavejester** [comment]
Also, I plan to release Compojure 1.0.0-RC1 within the next few days, and if all goes well, that RC should be promoted to 1.0.0 by the weekend.

**Comment by ghost** [comment]
Yes guys, I am sorry for the trouble. There must be something wrong in my project environment although for the moment I have no idea what it is. I have to dig a bit more. Will let you know..

Thank you.

**Comment by ghost** [comment]
Turns out my project did not recompile. I found out about this after I did a `lein deps && lein clean && lein compile`
Since I didn't ever do a `lein clean` before, the source of the problem was a bit hard to guess for me, as it was introduced a lot earlier in the dev process.

It seems that this line I had in my models, loading a common file was the culprit:

``` clojure
(load "base")
```

Used this instead

``` clojure
(load-file "src/proj/models/base.clj")
```

and it's all fine now.

**Comment by ghost** [comment]
Thank you guys for your wonderful work on the projects and for support.
