### ISSUE TITLE
session/put! fails because *noir-session* has no binding

### ISSUE THREAD

**Issue by rplevy** [noir-clojure/noir#59]
My understanding is that it should be possible to just call 

```
(session/put! :username "fred")
```

Or is it supposed to be necessary to define or dynamically bind _noir-session_ prior to putting into a session?  If that is the intended behavior then I guess it is just the documentation that is out of date, but if not, it should be an easy fix.  Just define a root binding for _noir-session_.

Is it implied that the mem atom should be bound to _noir-session_ by using wrap-noir-session as middleware?

---

Update: it seems to do this by default, however it is a little confusing at first that a session can't be set in the REPL, which is of course not a bug, just a consequence of this design choice.

**Comment by ibdknox** [comment]
It's not so much a design choice but an artifact of how the web works. What would a session mean outside the context of an HTTP request? If you just want to play around, check out noir.util.test/with-noir that will bind everything for you so you can pretend you're in a request :)

**Comment by rplevy** [comment]
True, that's a good way to look at it. :)
