### ISSUE TITLE
excludable dependencies (poor man's modularization)

### ISSUE THREAD

**Issue by shyblower** [noir-clojure/noir#64]
it would be great to have possibility to exclude certain dependencies you don't necessarily need in all circumstances (.i.e jetty when you utilize aleph). This could be done without splitting the project into separate modules like ring does.
You just have to "require" the specific package before you actually access parts of it instead of adding the "require" or "use" to the namespace header. Afterwards users of noir could exclude the dependency via leiningen.
This would help people who create standalone webapps in an ueberjar. It will shorten the startup time and make the jar smaller which is especially important if you put the app onto an embedded device (clojure works quite well with OpenJDK and JamVM on ARM devices like the sheeva-plug or dream-plug).

**Comment by ibdknox** [comment]
Done in alpha5 :)
