### ISSUE TITLE
Invalid code on the webnoir.org homepage

### ISSUE THREAD

**Issue by crittermike** [noir-clojure/noir#67]
(Not sure where else to put this).

On the webnoir.org homepage, the 4th code sample has the line:

```
 (let [items (all-todos)]
```

But (all-todos) isn't defined anywhere else on the page, so running it gives you "Unable to resolve symbol: all-todos in this context". Is that supposed to be left as an exercise for the reader or should that be fixed?

**Comment by bostonaholic** [comment]
I imagine that's pseudo-code. That function could be defined earlier in the file, or brought in from another namespace.

``` clojure
(defn all-todos []
  [{:id "todo1" :title "Get Milk" :due "today"}
   {:id "todo2" :title "Get Onions" :due "tomorrow"}])
```

**Comment by crittermike** [comment]
@bostonaholic thanks, yeah I imagine it probably wasn't meant to be included, but as a newbie to noir and clojure in general, stuff like that can definitely trip you up.

**Comment by ribeto** [comment]
Ran into this as well thanks for posting it
