### ISSUE TITLE
index.html file not served from public via root url

### ISSUE THREAD

**Issue by tobyhede** [noir-clojure/noir#82]
Placing an index.html file in the [resources/public directory] and accessing via the root url (http://localhost:8080/) results in an error on the server:

```
java.io.FileNotFoundException: /Project/resources/public (Is a directory)
```

The full path http://localhost:8080/index.html works, which is fine for now, but ideally the index.html would work as a default in the public directory.

**Comment by ibdknox** [comment]
Noir isn't meant to serve static sites, something like nginx will be several orders of magnitude faster for such things :)

In any case, if you want to do this, you'd just need to do:

``` clojure
(use 'noir.core)

(defpage "/" []
  (slurp "resources/public/index.html"))
```

**Comment by tobyhede** [comment]
Cheers. Looking at the underlying ring middleware, it does look like serving indexes of directories is standard behaviour - is this conflicting with noir's routing?

My intent hereis to use Noir to create services consumed by a JavaScript/Backbone app, so need a single page as a launchpad. In production would sit behind nginx or varnish.

**Comment by ibdknox** [comment]
Noir doesn't add the wrap-file middleware by default, you can add it though :)

``` clojure
(require '[ring.middleware.file :as ring-file])

(server/add-middleware wrap-file "resources/public/")
```

That gets you the desired behavior as well.

**Comment by tobyhede** [comment]
Oh right ... I just assumed that was how the resources were being
served from public
