### ISSUE TITLE
Missing UPGRADING

### ISSUE THREAD

**Issue by winks** [noir-clojure/noir#87]
Hey,
maybe I just didn't read closely enough, but I had a hard time getting back to noir after a hiatus of several months.

This is my old project:

[org.clojure/clojure "1.2.1"]
[noir "1.1.0"]

So when I got back just yesterday first thing I tried was using latest lein-noir and noir 1.2.2 and it took me several hours of random errors (I still can't pinpoint) until after reading the source when I found out I should've probably removed
:require [noir.pages :as pages]

I could be wrong of course, but if it really went poof, it would be nice to have a short UPGRADING file in the future that shows those little details. Could've happened to my old project as well if I just thought I'd try latest noir, without the "create project with old noir+leiningen and upgrade afterwards"

Additionally I'd suggest to make the use of "clojure 1.2.1" somewhere prominent, I was halfway trying to use 1.3.0 when I stumbled into this error.

Apart from that, rock on :)

**Comment by ibdknox** [comment]
Noir works just fine with Clojure 1.3.0 :) So have at it!

There's also a change log in the repo:
https://github.com/ibdknox/noir/blob/master/history.md
