### ISSUE TITLE
Use [cheshire "3.1.0"] since it does not depend on previous conflicting versions of Jackson

### ISSUE THREAD

**Issue by zoka** [noir-clojure/noir#88]
Due to the conflicts between 1.9.x and 1.5.0 versions of Jackson (a JSON Parser) it was not possible to have  clj-json and cheshire as indirect dependencies in a same project. This has been solved by  cheshire 3.1.0 since it depends on
Jackson 2.0.0 that has a different Java package name.

**Comment by Raynes** [comment]
The latest version of cheshire is 4.0.0 now.
